### PR TITLE
Allow passing process_group flag

### PR DESCRIPTION
**Pull request by samtay**

### CODE REVIEW

**Comment by GambolingPangolin** [comment]
At first glance, I like this idea.  @samtay Would you take some time to explain why you introduced this change (e.g. which problem you ran into) and spell out your goals for it?

**Comment by samtay** [comment]
We are building a dev tool at work that spins up various processes in parallel, one of which is the postgres process spawned by tmp-postgres. We wanted to be able to carefully control the behavior upon <kbd>Ctrl</kbd>+<kbd>C</kbd>, which wasn't possible without creating a new process group. (Without a new process group, a SIGINT to the main thread is simultaneously delivered to the postgres process.)

I figured it wouldn't hurt to support customizing one more field before [forwarding](https://github.com/jfischoff/tmp-postgres/blob/771207910bf2ca8843da2d3e0bff73b54a5e4686/src/Database/Postgres/Temp/Internal/Core.hs#L192-L198) the fields to [CreateProcess](https://hackage.haskell.org/package/process-1.6.10.0/docs/System-Process.html#t:CreateProcess), unless there is some reason to restrict this?

**Comment by GambolingPangolin** [comment]
This seems totally reasonable to me.  Would you add some Haddock comments that explain the practical effects of turning on create-group?

**Comment by jfischoff** [comment]
> I figured it wouldn't hurt to support customizing one more field before forwarding the fields to CreateProcess, unless there is some reason to restrict this?

One of the goals with `tmp-postgres` is to be able to override any default configuration, so I don't think there is a reason to restrict this. 

I'm fine accepting the PR as is. FWIW this is a minor version bump.

**Comment by GambolingPangolin** [comment]
@jfischoff IIUC, to comply with PVP this requires a major version increment.  We export the constructor for `ProcessConfig` and this changes its type.

**Comment by jfischoff** [comment]
Correct Ian. I’m not sure why I thought this backwards compatible

**Pull request merged**
